import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import { Toaster } from "@/components/ui/sonner";
import { FavoriteProvider } from "@/contexts/FavoriteProvider";
import { SessionProvider } from "@/contexts/sessionContext";
import { cookies } from "next/headers";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const roboto = Roboto({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Tea Biss",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/logo.png",
        href: "/logo.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/logo.png",
        href: "/logo.png",
      },
    ],
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const sessionToken = cookieStore.get("sessionToken");
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={`${roboto.className} bg-gray-100 relative`}>
        <NuqsAdapter>
          <SessionProvider initialSessionToken={sessionToken?.value}>
            <FavoriteProvider>
              <Header />
              {children}
            </FavoriteProvider>
            <Footer />
          </SessionProvider>
          <Toaster position="bottom-right" richColors />
        </NuqsAdapter>
      </body>
    </html>
  );
}
